name: Sync Main to Repo Branch
on:
  push:
    branches: [ main ]

jobs:
  sync-repo-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Push to repo branch
        env:
          GH_TOKEN: ${{ secrets.ACTION_PUSH_TOKEN }}
        run: |
          # git push origin HEAD:repo --force
          git push https://x-access-token:${GH_TOKEN}@github.com/cofedream/extensions-copymanga.git HEAD:repo --force
